import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GraphQLClient,gql } from 'graphql-request';

const graphcms = new GraphQLClient("https://api-eu-central-1.graphcms.com/v2/cl472djt32u1j01z3eg92gvb9/master")

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      </main>

    </div>
  )
}
